steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        'build',
        '-f', 'orchestrator/Dockerfile',
        '-t', 'asia-southeast1-docker.pkg.dev/cgh-icu-hd-roster-apr-2026/cloud-run-source-deploy/cgh-roster-benchmark-orchestrator:phase14d',
        '.'
      ]
images:
  - 'asia-southeast1-docker.pkg.dev/cgh-icu-hd-roster-apr-2026/cloud-run-source-deploy/cgh-roster-benchmark-orchestrator:phase14d'
